### ISSUE TITLE
Fix 'Animator is not playing an AnimatorController' warning

### ISSUE THREAD

**Issue by windcloak** [windcloak/BizarreAdventure#18]
The warning seems to constantly be there

![image](https://user-images.githubusercontent.com/40670609/113495319-80c0a680-94b6-11eb-9c1e-c39cc7466a4a.png)

**Comment by trent-magill** [comment]
closed as i believe this issue only happens in our testing map. i remade the enemies when making the desert and plains maps and dont get this error
