### ISSUE TITLE
need exit game button

### ISSUE THREAD

**Issue by trent-magill** [windcloak/BizarreAdventure#2]

**Comment by windcloak** [comment]
this should be in Intro/Win/Lose scene

**Comment by windcloak** [comment]
Commit ac1e22d

Added Quit button in IntroMenu

![image](https://user-images.githubusercontent.com/40670609/113493495-51ee0480-94a5-11eb-85c4-78279573bf66.png)

**Comment by windcloak** [comment]
Lose Screen

![image](https://user-images.githubusercontent.com/40670609/113497865-6cd46f00-94cd-11eb-9a58-633a6a44eb66.png)
